"""
Tipster consensus: reads public Telegram channels of trusted tipsters
(chosen by the operator, see config.settings.telegram_consensus_channels)
and turns their recent posts into an anonymous aggregate signal like
"4 de 6 tipsters monitorizados favorecen a Real Madrid" - never storing or
re-exposing a channel's literal wording, and never attributing a pick to a
specific tipster.

Status: built and tested, but INACTIVE in production. It needs two things
only the operator can provide:
1. TELEGRAM_CONSENSUS_SESSION in .env - generated by running
   scripts/telegram_consensus_login.py once, locally.
2. TELEGRAM_CONSENSUS_CHANNELS in .env - a comma-separated list of trusted
   channel usernames to monitor.

Nothing here is wired into src/analyzer/prompt_engine.py yet - see the
integration note in aggregator.py once real channels exist to validate
against.
"""
